// Java wrapper functions

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dragbase */

#ifndef _Included_dragbase
#define _Included_dragbase
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dragbase
 * Method:    Create_
 * Signature: (Ljava/lang/String;LSaveInterface;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_dragbase_Create_1
  (JNIEnv *, jobject, jstring, jobject, jstring);

/*
 * Class:     dragbase
 * Method:    SetFilename
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_dragbase_SetFilename
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
